title: Irmantas Burba
description: Mechanical Engineer / CAE Consultant
author:
  name: Irmantas Burba
  nickname: iburrb
  twitter: iburba
hostname:  # used to determine if google analytics should be triggered
url:  # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Irmantas Burba
  links:
    - https://twitter.com/iburba
    - https://github.com/iburrb
    - https://es.linkedin.com/in/irmantas-burba-3112a64a

twitter:
  username: iburba

# main page content
email:
  title: Contact Me
  href: "&#105;&#114;&#109;&#097;&#110;&#116;&#097;&#115;&#046;&#098;&#117;&#114;&#098;&#097;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;@

links:
  - name: github
    url: https://github.com/iburrb
    class: fab fa-github
  - name: twitter
    url: https://twitter.com/iburba
    class: fab fa-twitter
#  - name: blog
#    url: https://jimeh.io/
#    class: far fa-newspaper
  - name: linkedin
    url: https://es.linkedin.com/in/irmantas-burba-3112a64a
    class: fab fa-linkedin-in
#  - name: last.fm
#    url: https://www.last.fm/user/jimeh
#    class: fab fa-lastfm
#  - name: flickr
#    url: https://flickr.com/photos/jimeh
#    class: fab fa-flickr
#  - name: vcard
#    id: vcard
#    type: download
#    url: https://assets.jimeh.me/jim-myhrberg.vcf
#    class: far fa-address-card
#  - name: cv (pdf)
#    id: resume
#    type: download
#    url: https://assets.jimeh.me/jim-myhrberg-cv-5.0.0.pdf
#    class: fas fa-file-alt

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
